Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,17 +17,17 @@
 # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
 
 # gradle项目参考：https://docs.gitlab.com/ee/user/application_security/dependency_scanning/
-#include:
-#- template: SAST.gitlab-ci.yml
-#- template: Dependency-Scanning.gitlab-ci.yml
-#
-# #依赖检查
-# gemnasium-maven-dependency_scanning:
-#  tags: [ docker ]
-#
-##静态安全检查
-#semgrep-sast:
-# tags: [ docker ]
+include:
+- template: SAST.gitlab-ci.yml
+- template: Dependency-Scanning.gitlab-ci.yml
+
+#依赖检查
+gemnasium-maven-dependency_scanning:
+ tags: [ docker ]
+
+#静态安全检查
+semgrep-sast:
+tags: [ docker ]
 
 
 
@@ -37,120 +37,120 @@ stages:          # List of stages for jobs, and their order of execution
   - test
   - deploy
 
-test-job:
-  stage: test
-  script:
-    - sshpass -p $SSH_PASSWORD ssh -tt root@172.29.4.153
-
-#build-job: # This job runs in the build stage, which runs first.
-# stage: build
-# script:
-# - chmod +x gradlew
-# - ./gradlew build -x test
-
-# unit-test-job: # This job runs in the test stage.
-#   stage: test # It only starts when the job in the build stage completes successfully.
+# test-job:
+#   stage: test
 #   script:
-#     - chmod +x gradlew
-#     - ./gradlew test
-#   artifacts:
-#     when: always
-#     paths:
-#       - build/test-results/test/*.xml
-#     reports:
-#       junit: build/test-results/test/*.xml
-#
-#
-#
-# lint-test-job:   # This job also runs in the test stage.
-#  stage: test    # It can run at the same time as unit-test-job (in parallel).
-#  script:
-#    - echo "Linting code"
-#    - echo "No lint issues found."
-#
-# code_quality:
-#  stage: test
-#  image: docker:20.10.12
-#  allow_failure: true
-#  services:
-#    - name: 'docker:20.10.12-dind'
-#      command: ['--tls=false', '--host=tcp://0.0.0.0:2375']
-#  variables:
-#    DOCKER_DRIVER: overlay2
-#    DOCKER_CERT_PATH: ""
-#    DOCKER_TLS_CERTDIR: ""
-#    DOCKER_TLS_VERIFY: ""
-#    CODE_QUALITY_IMAGE_TAG: "0.96.0"
-#    CODE_QUALITY_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/ci-cd/codequality:$CODE_QUALITY_IMAGE_TAG"
-#    DOCKER_SOCKET_PATH: /var/run/docker.sock
-#  needs: []
-#  script:
-#    - export SOURCE_CODE=$PWD
-#    - |
-#      if ! docker info &>/dev/null; then
-#        if [ -z "$DOCKER_HOST" ] && [ -n "$KUBERNETES_PORT" ]; then
-#          export DOCKER_HOST='tcp://localhost:2375'
-#        fi
-#      fi
-#    - | # this is required to avoid undesirable reset of Docker image ENV variables being set on build stage
-#      function propagate_env_vars() {
-#        CURRENT_ENV=$(printenv)
-#
-#        for VAR_NAME; do
-#          echo $CURRENT_ENV | grep "${VAR_NAME}=" > /dev/null && echo "--env $VAR_NAME "
-#        done
-#      }
-#    - |
-#      if [ -n "$CODECLIMATE_REGISTRY_USERNAME" ] && [ -n "$CODECLIMATE_REGISTRY_PASSWORD" ] && [ -n "$CODECLIMATE_PREFIX" ]; then
-#        CODECLIMATE_REGISTRY=${CODECLIMATE_PREFIX%%/*}
-#        docker login "$CODECLIMATE_REGISTRY" --username "$CODECLIMATE_REGISTRY_USERNAME" --password "$CODECLIMATE_REGISTRY_PASSWORD"
-#      fi
-#    - docker pull --quiet "$CODE_QUALITY_IMAGE"
-#    - |
-#      docker run --rm \
-#        $(propagate_env_vars \
-#          SOURCE_CODE \
-#          TIMEOUT_SECONDS \
-#          CODECLIMATE_DEBUG \
-#          CODECLIMATE_DEV \
-#          REPORT_STDOUT \
-#          REPORT_FORMAT \
-#          ENGINE_MEMORY_LIMIT_BYTES \
-#          CODECLIMATE_PREFIX \
-#          CODECLIMATE_REGISTRY_USERNAME \
-#          CODECLIMATE_REGISTRY_PASSWORD \
-#          DOCKER_SOCKET_PATH \
-#        ) \
-#        --volume "$PWD":/code \
-#        --volume "$DOCKER_SOCKET_PATH":/var/run/docker.sock \
-#        "$CODE_QUALITY_IMAGE" /code
-#    - cat gl-code-quality-report.json
-#    - |
-#      if grep "issue" gl-code-quality-report.json
-#      then
-#        echo "Test fail"
-#        exit 1
-#      else
-#        echo "Test success"
-#        exit 0
-#      fi
-#  artifacts:
-#    reports:
-#      codequality: gl-code-quality-report.json
-#    expire_in: 1 week
-#  dependencies: []
-#  rules:
-#    - if: '$CODE_QUALITY_DISABLED'
-#      when: never
-#    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
+#     - sshpass -p $SSH_PASSWORD ssh -tt root@172.29.4.153
+
+build-job: # This job runs in the build stage, which runs first.
+stage: build
+script:
+- chmod +x gradlew
+- ./gradlew build -x test
+
+unit-test-job: # This job runs in the test stage.
+  stage: test # It only starts when the job in the build stage completes successfully.
+  script:
+    - chmod +x gradlew
+    - ./gradlew test
+  artifacts:
+    when: always
+    paths:
+      - build/test-results/test/*.xml
+    reports:
+      junit: build/test-results/test/*.xml
+
+
+
+lint-test-job:   # This job also runs in the test stage.
+ stage: test    # It can run at the same time as unit-test-job (in parallel).
+ script:
+   - echo "Linting code"
+   - echo "No lint issues found."
+
+code_quality:
+ stage: test
+ image: docker:20.10.12
+ allow_failure: true
+ services:
+   - name: 'docker:20.10.12-dind'
+     command: ['--tls=false', '--host=tcp://0.0.0.0:2375']
+ variables:
+   DOCKER_DRIVER: overlay2
+   DOCKER_CERT_PATH: ""
+   DOCKER_TLS_CERTDIR: ""
+   DOCKER_TLS_VERIFY: ""
+   CODE_QUALITY_IMAGE_TAG: "0.96.0"
+   CODE_QUALITY_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/ci-cd/codequality:$CODE_QUALITY_IMAGE_TAG"
+   DOCKER_SOCKET_PATH: /var/run/docker.sock
+ needs: []
+ script:
+   - export SOURCE_CODE=$PWD
+   - |
+     if ! docker info &>/dev/null; then
+       if [ -z "$DOCKER_HOST" ] && [ -n "$KUBERNETES_PORT" ]; then
+         export DOCKER_HOST='tcp://localhost:2375'
+       fi
+     fi
+   - | # this is required to avoid undesirable reset of Docker image ENV variables being set on build stage
+     function propagate_env_vars() {
+       CURRENT_ENV=$(printenv)
+
+       for VAR_NAME; do
+         echo $CURRENT_ENV | grep "${VAR_NAME}=" > /dev/null && echo "--env $VAR_NAME "
+       done
+     }
+   - |
+     if [ -n "$CODECLIMATE_REGISTRY_USERNAME" ] && [ -n "$CODECLIMATE_REGISTRY_PASSWORD" ] && [ -n "$CODECLIMATE_PREFIX" ]; then
+       CODECLIMATE_REGISTRY=${CODECLIMATE_PREFIX%%/*}
+       docker login "$CODECLIMATE_REGISTRY" --username "$CODECLIMATE_REGISTRY_USERNAME" --password "$CODECLIMATE_REGISTRY_PASSWORD"
+     fi
+   - docker pull --quiet "$CODE_QUALITY_IMAGE"
+   - |
+     docker run --rm \
+       $(propagate_env_vars \
+         SOURCE_CODE \
+         TIMEOUT_SECONDS \
+         CODECLIMATE_DEBUG \
+         CODECLIMATE_DEV \
+         REPORT_STDOUT \
+         REPORT_FORMAT \
+         ENGINE_MEMORY_LIMIT_BYTES \
+         CODECLIMATE_PREFIX \
+         CODECLIMATE_REGISTRY_USERNAME \
+         CODECLIMATE_REGISTRY_PASSWORD \
+         DOCKER_SOCKET_PATH \
+       ) \
+       --volume "$PWD":/code \
+       --volume "$DOCKER_SOCKET_PATH":/var/run/docker.sock \
+       "$CODE_QUALITY_IMAGE" /code
+   - cat gl-code-quality-report.json
+   - |
+     if grep "issue" gl-code-quality-report.json
+     then
+       echo "Test fail"
+       exit 1
+     else
+       echo "Test success"
+       exit 0
+     fi
+ artifacts:
+   reports:
+     codequality: gl-code-quality-report.json
+   expire_in: 1 week
+ dependencies: []
+ rules:
+   - if: '$CODE_QUALITY_DISABLED'
+     when: never
+   - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
 
 # This job runs in the deploy stage.
 # It only runs when *both* jobs in the test stage
-#deploy-job:
-#  stage: deploy
-#  environment: production
-#  script:
-#    - chmod +x gradlew
-#    - ./gradlew build -x test
-#    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no build/libs/l23o6-0.0.1-snapshot.jar root@172.29.4.153:~
-#    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@172.29.4.153 "killall java;screen -d -m java -jar l23o6-0.0.1-snapshot.jar"
+deploy-job:
+ stage: deploy
+ environment: production
+ script:
+   - chmod +x gradlew
+   - ./gradlew build -x test
+   - sshpass -p "MQGcudeM" scp -o StrictHostKeyChecking=no build/libs/l23o6-0.0.1-snapshot.jar root@172.29.4.153:~
+   - sshpass -p "MQGcudeM" ssh -o StrictHostKeyChecking=no root@172.29.4.153 "killall java;screen -d -m java -jar l23o6-0.0.1-snapshot.jar"
